// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: copyfrom.go

package sql

import (
	"context"
)

// iteratorForInsertSkill implements pgx.CopyFromSource.
type iteratorForInsertSkill struct {
	rows                 []InsertSkillParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSkill) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSkill) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Encounter,
		r.rows[0].Player,
		r.rows[0].SkillID,
		r.rows[0].Dps,
		r.rows[0].Damage,
		r.rows[0].Name,
		r.rows[0].Tripods,
		r.rows[0].Fields,
	}, nil
}

func (r iteratorForInsertSkill) Err() error {
	return nil
}

func (q *Queries) InsertSkill(ctx context.Context, arg []InsertSkillParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"skills"}, []string{"encounter", "player", "skill_id", "dps", "damage", "name", "tripods", "fields"}, &iteratorForInsertSkill{rows: arg})
}
