// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sql

import (
	structs "github.com/0fau/logs/pkg/database/sql/structs"
	"github.com/jackc/pgx/v5/pgtype"
)

type Encounter struct {
	ID          int32
	UploadedBy  pgtype.UUID
	UploadedAt  pgtype.Timestamp
	Settings    structs.EncounterSettings
	Tags        []string
	Header      structs.EncounterHeader
	Data        structs.EncounterData
	UniqueHash  string
	UniqueGroup int32
	Boss        string
	Difficulty  string
	Date        pgtype.Timestamp
	Duration    int32
	LocalPlayer string
}

type GroupedEncounter struct {
	GroupID   int32
	Uploaders []pgtype.UUID
}

type Player struct {
	Encounter int32
	Class     string
	Name      string
	Dead      bool
	Data      structs.IndexedPlayerData
	Place     int32
}

type User struct {
	ID          pgtype.UUID
	Username    pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	AccessToken pgtype.Text
	DiscordID   string
	DiscordTag  string
	Avatar      pgtype.Text
	Friends     []pgtype.UUID
	Settings    structs.UserSettings
	Titles      []string
	Roles       []string
}
