apiVersion: v1
kind: Service
metadata:
  name: logsbyfaust
  namespace: logsbyfaust
spec:
  selector:
    app: logsbyfaust
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: api
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: admin
      protocol: TCP
      port: 3010
      targetPort: 3010